const c = @import("c.zig");

pub const Blend2DError = error{
    OutOfMemory,
    InvalidValue,
    InvalidState,
    InvalidHandle,
    InvalidConversion,
    Overflow,
    NotInitialized,
    NotImplemented,
    NotPermitted,
    IO,
    Busy,
    Interrupted,
    TryAgain,
    TimedOut,
    BrokenPipe,
    SymlinkLoop,
    FileTooLarge,
    AlreadyExists,
    AccessDenied,
    MediaChanged,
    ReadOnlyFS,
    NoDevice,
    NoEntry,
    NoMedia,
    NoMoreData,
    NoMoreFiles,
    NoSpaceLeft,
    NotEmpty,
    NotFile,
    NotDirectory,
    NotSameDevice,
    NotBlockDevice,
    InvalidFileName,
    FileNameTooLong,
    TooManyOpenFiles,
    TooManyOpenFilesByOs,
    TooManyLinks,
    TooManyThreads,
    ThreadPoolExhausted,
    FileEmpty,
    OpenFailed,
    NotRootDevice,
    UnknownSystemError,
    InvalidAlignment,
    InvalidSignature,
    InvalidData,
    InvalidString,
    InvalidKey,
    DataTrucated,
    DataTooLarge,
    DecompressionFailded,
    InvalidGeometry,
    NoMatchingVertex,

    InvalidCreateFlags,
    NoMatchingCookie,
    NoStateToRestore,
    TooManySavedStates,

    ImageTooLarge,
    ImageNoMatchingCodec,
    ImageUnknownFileFormat,
    ImageDecoderNotProvided,
    ImageEncoderNotProvided,

    PngMultipleIHDR,
    PngInvalidIDAT,
    PngInvalidIEND,
    PngInvalidPLTE,
    PngInvalidTRNS,
    PngInvalidFilter,

    JpegUnsupportedFeature,
    JpegInvalidSOS,
    JpegInvalidSOF,
    JpegMultipleSOF,
    JpegUnsupportedSOF,

    FontNotInitialized,
    FontNoMatch,
    FontNoCharacterMapping,
    FontMissingImportantTable,
    FontFeatureNotAvailable,
    FontCFFInvalidData,
    FontProgramTerminated,

    GlyphSubstitutionTooLarge,
    InvalidGlyph,

    Unknown,
};

pub fn makeZigError(result: c.BLResult) Blend2DError!void {
    return switch (result) {
        c.BL_SUCCESS => {},
        // General Errors
        c.BL_ERROR_OUT_OF_MEMORY => Blend2DError.OutOfMemory,
        c.BL_ERROR_INVALID_VALUE => Blend2DError.InvalidValue,
        c.BL_ERROR_INVALID_STATE => Blend2DError.InvalidState,
        c.BL_ERROR_INVALID_HANDLE => Blend2DError.InvalidHandle,
        c.BL_ERROR_INVALID_CONVERSION => Blend2DError.InvalidConversion,
        c.BL_ERROR_OVERFLOW => Blend2DError.Overflow,
        c.BL_ERROR_NOT_INITIALIZED => Blend2DError.NotInitialized,
        c.BL_ERROR_NOT_IMPLEMENTED => Blend2DError.NotImplemented,
        c.BL_ERROR_NOT_PERMITTED => Blend2DError.NotPermitted,
        c.BL_ERROR_IO => Blend2DError.IO,
        c.BL_ERROR_BUSY => Blend2DError.Busy,
        c.BL_ERROR_INTERRUPTED => Blend2DError.Interrupted,
        c.BL_ERROR_TRY_AGAIN => Blend2DError.TryAgain,
        c.BL_ERROR_TIMED_OUT => Blend2DError.TimedOut,
        c.BL_ERROR_BROKEN_PIPE => Blend2DError.BrokenPipe,
        c.BL_ERROR_SYMLINK_LOOP => Blend2DError.SymlinkLoop,
        c.BL_ERROR_FILE_TOO_LARGE => Blend2DError.FileTooLarge,
        c.BL_ERROR_ALREADY_EXISTS => Blend2DError.AlreadyExists,
        c.BL_ERROR_ACCESS_DENIED => Blend2DError.AccessDenied,
        c.BL_ERROR_MEDIA_CHANGED => Blend2DError.MediaChanged,
        c.BL_ERROR_READ_ONLY_FS => Blend2DError.ReadOnlyFS,
        c.BL_ERROR_NO_DEVICE => Blend2DError.NoDevice,
        c.BL_ERROR_NO_ENTRY => Blend2DError.NoEntry,
        c.BL_ERROR_NO_MEDIA => Blend2DError.NoMedia,
        c.BL_ERROR_NO_MORE_DATA => Blend2DError.NoMoreData,
        c.BL_ERROR_NO_MORE_FILES => Blend2DError.NoMoreFiles,
        c.BL_ERROR_NO_SPACE_LEFT => Blend2DError.NoSpaceLeft,
        c.BL_ERROR_NOT_EMPTY => Blend2DError.NotEmpty,
        c.BL_ERROR_NOT_FILE => Blend2DError.NotFile,
        c.BL_ERROR_NOT_DIRECTORY => Blend2DError.NotDirectory,
        c.BL_ERROR_NOT_SAME_DEVICE => Blend2DError.NotSameDevice,
        c.BL_ERROR_NOT_BLOCK_DEVICE => Blend2DError.NotBlockDevice,
        c.BL_ERROR_INVALID_FILE_NAME => Blend2DError.InvalidFileName,
        c.BL_ERROR_FILE_NAME_TOO_LONG => Blend2DError.FileNameTooLong,
        c.BL_ERROR_TOO_MANY_OPEN_FILES => Blend2DError.TooManyOpenFiles,
        c.BL_ERROR_TOO_MANY_OPEN_FILES_BY_OS => Blend2DError.TooManyOpenFilesByOs,
        c.BL_ERROR_TOO_MANY_LINKS => Blend2DError.TooManyLinks,
        c.BL_ERROR_TOO_MANY_THREADS => Blend2DError.TooManyThreads,
        c.BL_ERROR_THREAD_POOL_EXHAUSTED => Blend2DError.ThreadPoolExhausted,
        c.BL_ERROR_FILE_EMPTY => Blend2DError.FileEmpty,
        c.BL_ERROR_OPEN_FAILED => Blend2DError.OpenFailed,
        c.BL_ERROR_NOT_ROOT_DEVICE => Blend2DError.NotRootDevice,
        c.BL_ERROR_UNKNOWN_SYSTEM_ERROR => Blend2DError.UnknownSystemError,
        c.BL_ERROR_INVALID_ALIGNMENT => Blend2DError.InvalidAlignment,
        c.BL_ERROR_INVALID_SIGNATURE => Blend2DError.InvalidSignature,
        c.BL_ERROR_INVALID_DATA => Blend2DError.InvalidData,
        c.BL_ERROR_INVALID_STRING => Blend2DError.InvalidString,
        c.BL_ERROR_INVALID_KEY => Blend2DError.InvalidKey,
        c.BL_ERROR_DATA_TRUNCATED => Blend2DError.DataTrucated,
        c.BL_ERROR_DATA_TOO_LARGE => Blend2DError.DataTooLarge,
        c.BL_ERROR_DECOMPRESSION_FAILED => Blend2DError.DecompressionFailded,
        c.BL_ERROR_INVALID_GEOMETRY => Blend2DError.InvalidGeometry,
        c.BL_ERROR_NO_MATCHING_VERTEX => Blend2DError.NoMatchingVertex,

        // Context Errors
        c.BL_ERROR_INVALID_CREATE_FLAGS => Blend2DError.InvalidCreateFlags,
        c.BL_ERROR_NO_MATCHING_COOKIE => Blend2DError.NoMatchingCookie,
        c.BL_ERROR_NO_STATES_TO_RESTORE => Blend2DError.NoStateToRestore,
        c.BL_ERROR_TOO_MANY_SAVED_STATES => Blend2DError.TooManySavedStates,

        // Image Errors
        c.BL_ERROR_IMAGE_TOO_LARGE => Blend2DError.ImageTooLarge,
        c.BL_ERROR_IMAGE_NO_MATCHING_CODEC => Blend2DError.ImageNoMatchingCodec,
        c.BL_ERROR_IMAGE_UNKNOWN_FILE_FORMAT => Blend2DError.ImageUnknownFileFormat,
        c.BL_ERROR_IMAGE_DECODER_NOT_PROVIDED => Blend2DError.ImageDecoderNotProvided,
        c.BL_ERROR_IMAGE_ENCODER_NOT_PROVIDED => Blend2DError.ImageEncoderNotProvided,

        // Png Errors
        c.BL_ERROR_PNG_MULTIPLE_IHDR => Blend2DError.PngMultipleIHDR,
        c.BL_ERROR_PNG_INVALID_IDAT => Blend2DError.PngInvalidIDAT,
        c.BL_ERROR_PNG_INVALID_IEND => Blend2DError.PngInvalidIEND,
        c.BL_ERROR_PNG_INVALID_PLTE => Blend2DError.PngInvalidPLTE,
        c.BL_ERROR_PNG_INVALID_TRNS => Blend2DError.PngInvalidTRNS,
        c.BL_ERROR_PNG_INVALID_FILTER => Blend2DError.PngInvalidFilter,

        // Jpeg Errors
        c.BL_ERROR_JPEG_UNSUPPORTED_FEATURE => Blend2DError.JpegUnsupportedFeature,
        c.BL_ERROR_JPEG_INVALID_SOS => Blend2DError.JpegInvalidSOS,
        c.BL_ERROR_JPEG_INVALID_SOF => Blend2DError.JpegInvalidSOF,
        c.BL_ERROR_JPEG_MULTIPLE_SOF => Blend2DError.JpegMultipleSOF,
        c.BL_ERROR_JPEG_UNSUPPORTED_SOF => Blend2DError.JpegUnsupportedSOF,

        // Font Errors
        c.BL_ERROR_FONT_NOT_INITIALIZED => Blend2DError.FontNotInitialized,
        c.BL_ERROR_FONT_NO_MATCH => Blend2DError.FontNoMatch,
        c.BL_ERROR_FONT_NO_CHARACTER_MAPPING => Blend2DError.FontNoCharacterMapping,
        c.BL_ERROR_FONT_MISSING_IMPORTANT_TABLE => Blend2DError.FontMissingImportantTable,
        c.BL_ERROR_FONT_FEATURE_NOT_AVAILABLE => Blend2DError.FontFeatureNotAvailable,
        c.BL_ERROR_FONT_CFF_INVALID_DATA => Blend2DError.FontCFFInvalidData,
        c.BL_ERROR_FONT_PROGRAM_TERMINATED => Blend2DError.FontProgramTerminated,

        c.BL_ERROR_GLYPH_SUBSTITUTION_TOO_LARGE => Blend2DError.GlyphSubstitutionTooLarge,
        c.BL_ERROR_INVALID_GLYPH => Blend2DError.InvalidGlyph,

        else => return Blend2DError.Unknown,
    };
}
